[package]
name = "yara-kiosk"
version = "0.4.1"
edition = "2021"

[lib]
name = "yara_kiosk_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"
tauri-plugin-opener = "2"
tauri-plugin-fs = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
tokio = { version = "1", features = ["full"] }
rayon = "1"
walkdir = "2"
memmap2 = "0.9"
yara-x = { version = "1.16", features = ["native-code-serialization"] }
zip = { version = "8", default-features = false, features = ["deflate"] }
sha2 = "0.11"
hex = "0.4"
reqwest = { version = "0.13", features = ["json", "query", "rustls"], default-features = false }
uuid = { version = "1", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
dirs = "6"
anyhow = "1"
log = "0.4"
env_logger = "0.11"

[target.'cfg(unix)'.dependencies]
pam = "0.8"
libc = "0.2"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.62", features = [
    "Win32_Storage_FileSystem",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_WindowsProgramming",
] }

[profile.release]
opt-level = "s"
strip = true
lto = true
